version: '3.9'
services:
  tokengenerator-api:
    build: 
      context: './CMSTokenGeneratorAPI'
      dockerfile: Dockerfile
    container_name: tokengenerator-api
    expose:
      - 5000
    restart : always
    networks:
      - nginx-network
  nginx-tokengenerator:
    image: nginx:latest
    container_name: tokengenerator-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    restart : always
    depends_on:
      - tokengenerator-api
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge

