version: '3.9'
services:
  tokengenerator-api:
    build: 
      context: './CMSTokenGeneratorAPI'
      dockerfile: Dockerfile
    container_name: tokengenerator-api
    volumes:
      - ./connection.json:/app/connection/connection.json
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart : unless-stopped
    networks:
      - nginx-network
      - personal-web-api_db-network
  nginx-tokengenerator:
    image: nginx:latest
    container_name: tokengenerator-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5001:80
    restart : unless-stopped
    depends_on:
      - tokengenerator-api
    networks:
      - nginx-network
      - personal-web-api_db-network
networks:
  nginx-network:
    driver: bridge
  personal-web-api_db-network:
    external: true